### ISSUE TITLE
Some bugs on conversation with NPC

### ISSUE THREAD

**Issue by volcani** [comphack/datastore#1]
I've just started to play with private server, but it looks like some event with NPC have some bugs.

For Example, in Act.0, Kuroe repeats passage before choice which reaction player take.
Some NPC looks like having same problem.

**Comment by Fizzlybub** [comment]
We have recordings of both messages being used as a response to いいえ, so it seems that CAVE changed the message order for this NPC in late 2012 from
Message:
……守衛の出迎えどころか、 姿すら確認出来ず……か。
……さて、
では、まず何から始めようか。
Prompt:
では、まず何から始めようか。

to
Message:
では、まず何から始めようか。
Prompt:
では、まず何から始めようか。

I will change the message to match the later version.
